version: '3.8'

services:
    nodejs:
        image: node:17-alpine
        container_name: cdiary_nodejs
        working_dir: /var/www/
        volumes:
            - .:/var/www/

    webserver:
        image: nginx:alpine
        container_name: cdiary_webserver
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - ./docker/var/log/nginx:/var/log/nginx
